import { parsePhoneNumberFromString } from "libphonenumber-js";

export type CountryDialCodeOption = {
  country: string;
  dialCode: string;
  iso2: string;
};

// Country calling codes for a native <select> dropdown.
// Note: Some territories share a calling code (e.g., +1 NANP).
export const COUNTRY_DIAL_CODES: CountryDialCodeOption[] = [
  { country: "Afghanistan", dialCode: "+93", iso2: "AF" },
  { country: "Albania", dialCode: "+355", iso2: "AL" },
  { country: "Algeria", dialCode: "+213", iso2: "DZ" },
  { country: "American Samoa", dialCode: "+1", iso2: "AS" },
  { country: "Andorra", dialCode: "+376", iso2: "AD" },
  { country: "Angola", dialCode: "+244", iso2: "AO" },
  { country: "Anguilla", dialCode: "+1", iso2: "AI" },
  { country: "Antigua and Barbuda", dialCode: "+1", iso2: "AG" },
  { country: "Argentina", dialCode: "+54", iso2: "AR" },
  { country: "Armenia", dialCode: "+374", iso2: "AM" },
  { country: "Aruba", dialCode: "+297", iso2: "AW" },
  { country: "Australia", dialCode: "+61", iso2: "AU" },
  { country: "Austria", dialCode: "+43", iso2: "AT" },
  { country: "Azerbaijan", dialCode: "+994", iso2: "AZ" },
  { country: "Bahamas", dialCode: "+1", iso2: "BS" },
  { country: "Bahrain", dialCode: "+973", iso2: "BH" },
  { country: "Bangladesh", dialCode: "+880", iso2: "BD" },
  { country: "Barbados", dialCode: "+1", iso2: "BB" },
  { country: "Belarus", dialCode: "+375", iso2: "BY" },
  { country: "Belgium", dialCode: "+32", iso2: "BE" },
  { country: "Belize", dialCode: "+501", iso2: "BZ" },
  { country: "Benin", dialCode: "+229", iso2: "BJ" },
  { country: "Bermuda", dialCode: "+1", iso2: "BM" },
  { country: "Bhutan", dialCode: "+975", iso2: "BT" },
  { country: "Bolivia", dialCode: "+591", iso2: "BO" },
  { country: "Bosnia and Herzegovina", dialCode: "+387", iso2: "BA" },
  { country: "Botswana", dialCode: "+267", iso2: "BW" },
  { country: "Brazil", dialCode: "+55", iso2: "BR" },
  { country: "British Virgin Islands", dialCode: "+1", iso2: "VG" },
  { country: "Brunei", dialCode: "+673", iso2: "BN" },
  { country: "Bulgaria", dialCode: "+359", iso2: "BG" },
  { country: "Burkina Faso", dialCode: "+226", iso2: "BF" },
  { country: "Burundi", dialCode: "+257", iso2: "BI" },
  { country: "Cambodia", dialCode: "+855", iso2: "KH" },
  { country: "Cameroon", dialCode: "+237", iso2: "CM" },
  { country: "Canada", dialCode: "+1", iso2: "CA" },
  { country: "Cape Verde", dialCode: "+238", iso2: "CV" },
  { country: "Cayman Islands", dialCode: "+1", iso2: "KY" },
  { country: "Central African Republic", dialCode: "+236", iso2: "CF" },
  { country: "Chad", dialCode: "+235", iso2: "TD" },
  { country: "Chile", dialCode: "+56", iso2: "CL" },
  { country: "China", dialCode: "+86", iso2: "CN" },
  { country: "Colombia", dialCode: "+57", iso2: "CO" },
  { country: "Comoros", dialCode: "+269", iso2: "KM" },
  { country: "Congo (DRC)", dialCode: "+243", iso2: "CD" },
  { country: "Congo (Republic)", dialCode: "+242", iso2: "CG" },
  { country: "Cook Islands", dialCode: "+682", iso2: "CK" },
  { country: "Costa Rica", dialCode: "+506", iso2: "CR" },
  { country: "Côte d’Ivoire", dialCode: "+225", iso2: "CI" },
  { country: "Croatia", dialCode: "+385", iso2: "HR" },
  { country: "Cuba", dialCode: "+53", iso2: "CU" },
  { country: "Curaçao", dialCode: "+599", iso2: "CW" },
  { country: "Cyprus", dialCode: "+357", iso2: "CY" },
  { country: "Czechia", dialCode: "+420", iso2: "CZ" },
  { country: "Denmark", dialCode: "+45", iso2: "DK" },
  { country: "Djibouti", dialCode: "+253", iso2: "DJ" },
  { country: "Dominica", dialCode: "+1", iso2: "DM" },
  { country: "Dominican Republic", dialCode: "+1", iso2: "DO" },
  { country: "Ecuador", dialCode: "+593", iso2: "EC" },
  { country: "Egypt", dialCode: "+20", iso2: "EG" },
  { country: "El Salvador", dialCode: "+503", iso2: "SV" },
  { country: "Equatorial Guinea", dialCode: "+240", iso2: "GQ" },
  { country: "Eritrea", dialCode: "+291", iso2: "ER" },
  { country: "Estonia", dialCode: "+372", iso2: "EE" },
  { country: "Eswatini", dialCode: "+268", iso2: "SZ" },
  { country: "Ethiopia", dialCode: "+251", iso2: "ET" },
  { country: "Falkland Islands", dialCode: "+500", iso2: "FK" },
  { country: "Faroe Islands", dialCode: "+298", iso2: "FO" },
  { country: "Fiji", dialCode: "+679", iso2: "FJ" },
  { country: "Finland", dialCode: "+358", iso2: "FI" },
  { country: "France", dialCode: "+33", iso2: "FR" },
  { country: "French Guiana", dialCode: "+594", iso2: "GF" },
  { country: "French Polynesia", dialCode: "+689", iso2: "PF" },
  { country: "Gabon", dialCode: "+241", iso2: "GA" },
  { country: "Gambia", dialCode: "+220", iso2: "GM" },
  { country: "Georgia", dialCode: "+995", iso2: "GE" },
  { country: "Germany", dialCode: "+49", iso2: "DE" },
  { country: "Ghana", dialCode: "+233", iso2: "GH" },
  { country: "Gibraltar", dialCode: "+350", iso2: "GI" },
  { country: "Greece", dialCode: "+30", iso2: "GR" },
  { country: "Greenland", dialCode: "+299", iso2: "GL" },
  { country: "Grenada", dialCode: "+1", iso2: "GD" },
  { country: "Guadeloupe", dialCode: "+590", iso2: "GP" },
  { country: "Guam", dialCode: "+1", iso2: "GU" },
  { country: "Guatemala", dialCode: "+502", iso2: "GT" },
  { country: "Guernsey", dialCode: "+44", iso2: "GG" },
  { country: "Guinea", dialCode: "+224", iso2: "GN" },
  { country: "Guinea-Bissau", dialCode: "+245", iso2: "GW" },
  { country: "Guyana", dialCode: "+592", iso2: "GY" },
  { country: "Haiti", dialCode: "+509", iso2: "HT" },
  { country: "Honduras", dialCode: "+504", iso2: "HN" },
  { country: "Hong Kong", dialCode: "+852", iso2: "HK" },
  { country: "Hungary", dialCode: "+36", iso2: "HU" },
  { country: "Iceland", dialCode: "+354", iso2: "IS" },
  { country: "India", dialCode: "+91", iso2: "IN" },
  { country: "Indonesia", dialCode: "+62", iso2: "ID" },
  { country: "Iran", dialCode: "+98", iso2: "IR" },
  { country: "Iraq", dialCode: "+964", iso2: "IQ" },
  { country: "Ireland", dialCode: "+353", iso2: "IE" },
  { country: "Isle of Man", dialCode: "+44", iso2: "IM" },
  { country: "Israel", dialCode: "+972", iso2: "IL" },
  { country: "Italy", dialCode: "+39", iso2: "IT" },
  { country: "Jamaica", dialCode: "+1", iso2: "JM" },
  { country: "Japan", dialCode: "+81", iso2: "JP" },
  { country: "Jersey", dialCode: "+44", iso2: "JE" },
  { country: "Jordan", dialCode: "+962", iso2: "JO" },
  { country: "Kazakhstan", dialCode: "+7", iso2: "KZ" },
  { country: "Kenya", dialCode: "+254", iso2: "KE" },
  { country: "Kiribati", dialCode: "+686", iso2: "KI" },
  { country: "Kuwait", dialCode: "+965", iso2: "KW" },
  { country: "Kyrgyzstan", dialCode: "+996", iso2: "KG" },
  { country: "Laos", dialCode: "+856", iso2: "LA" },
  { country: "Latvia", dialCode: "+371", iso2: "LV" },
  { country: "Lebanon", dialCode: "+961", iso2: "LB" },
  { country: "Lesotho", dialCode: "+266", iso2: "LS" },
  { country: "Liberia", dialCode: "+231", iso2: "LR" },
  { country: "Libya", dialCode: "+218", iso2: "LY" },
  { country: "Liechtenstein", dialCode: "+423", iso2: "LI" },
  { country: "Lithuania", dialCode: "+370", iso2: "LT" },
  { country: "Luxembourg", dialCode: "+352", iso2: "LU" },
  { country: "Macau", dialCode: "+853", iso2: "MO" },
  { country: "Madagascar", dialCode: "+261", iso2: "MG" },
  { country: "Malawi", dialCode: "+265", iso2: "MW" },
  { country: "Malaysia", dialCode: "+60", iso2: "MY" },
  { country: "Maldives", dialCode: "+960", iso2: "MV" },
  { country: "Mali", dialCode: "+223", iso2: "ML" },
  { country: "Malta", dialCode: "+356", iso2: "MT" },
  { country: "Marshall Islands", dialCode: "+692", iso2: "MH" },
  { country: "Martinique", dialCode: "+596", iso2: "MQ" },
  { country: "Mauritania", dialCode: "+222", iso2: "MR" },
  { country: "Mauritius", dialCode: "+230", iso2: "MU" },
  { country: "Mayotte", dialCode: "+262", iso2: "YT" },
  { country: "Mexico", dialCode: "+52", iso2: "MX" },
  { country: "Micronesia", dialCode: "+691", iso2: "FM" },
  { country: "Moldova", dialCode: "+373", iso2: "MD" },
  { country: "Monaco", dialCode: "+377", iso2: "MC" },
  { country: "Mongolia", dialCode: "+976", iso2: "MN" },
  { country: "Montenegro", dialCode: "+382", iso2: "ME" },
  { country: "Montserrat", dialCode: "+1", iso2: "MS" },
  { country: "Morocco", dialCode: "+212", iso2: "MA" },
  { country: "Mozambique", dialCode: "+258", iso2: "MZ" },
  { country: "Myanmar", dialCode: "+95", iso2: "MM" },
  { country: "Namibia", dialCode: "+264", iso2: "NA" },
  { country: "Nauru", dialCode: "+674", iso2: "NR" },
  { country: "Nepal", dialCode: "+977", iso2: "NP" },
  { country: "Netherlands", dialCode: "+31", iso2: "NL" },
  { country: "New Caledonia", dialCode: "+687", iso2: "NC" },
  { country: "New Zealand", dialCode: "+64", iso2: "NZ" },
  { country: "Nicaragua", dialCode: "+505", iso2: "NI" },
  { country: "Niger", dialCode: "+227", iso2: "NE" },
  { country: "Nigeria", dialCode: "+234", iso2: "NG" },
  { country: "Niue", dialCode: "+683", iso2: "NU" },
  { country: "North Macedonia", dialCode: "+389", iso2: "MK" },
  { country: "Northern Mariana Islands", dialCode: "+1", iso2: "MP" },
  { country: "Norway", dialCode: "+47", iso2: "NO" },
  { country: "Oman", dialCode: "+968", iso2: "OM" },
  { country: "Pakistan", dialCode: "+92", iso2: "PK" },
  { country: "Palau", dialCode: "+680", iso2: "PW" },
  { country: "Palestine", dialCode: "+970", iso2: "PS" },
  { country: "Panama", dialCode: "+507", iso2: "PA" },
  { country: "Papua New Guinea", dialCode: "+675", iso2: "PG" },
  { country: "Paraguay", dialCode: "+595", iso2: "PY" },
  { country: "Peru", dialCode: "+51", iso2: "PE" },
  { country: "Philippines", dialCode: "+63", iso2: "PH" },
  { country: "Poland", dialCode: "+48", iso2: "PL" },
  { country: "Portugal", dialCode: "+351", iso2: "PT" },
  { country: "Puerto Rico", dialCode: "+1", iso2: "PR" },
  { country: "Qatar", dialCode: "+974", iso2: "QA" },
  { country: "Réunion", dialCode: "+262", iso2: "RE" },
  { country: "Romania", dialCode: "+40", iso2: "RO" },
  { country: "Russia", dialCode: "+7", iso2: "RU" },
  { country: "Rwanda", dialCode: "+250", iso2: "RW" },
  { country: "Saint Kitts and Nevis", dialCode: "+1", iso2: "KN" },
  { country: "Saint Lucia", dialCode: "+1", iso2: "LC" },
  { country: "Saint Martin", dialCode: "+590", iso2: "MF" },
  { country: "Saint Pierre and Miquelon", dialCode: "+508", iso2: "PM" },
  { country: "Saint Vincent and the Grenadines", dialCode: "+1", iso2: "VC" },
  { country: "Samoa", dialCode: "+685", iso2: "WS" },
  { country: "San Marino", dialCode: "+378", iso2: "SM" },
  { country: "São Tomé and Príncipe", dialCode: "+239", iso2: "ST" },
  { country: "Saudi Arabia", dialCode: "+966", iso2: "SA" },
  { country: "Senegal", dialCode: "+221", iso2: "SN" },
  { country: "Serbia", dialCode: "+381", iso2: "RS" },
  { country: "Seychelles", dialCode: "+248", iso2: "SC" },
  { country: "Sierra Leone", dialCode: "+232", iso2: "SL" },
  { country: "Singapore", dialCode: "+65", iso2: "SG" },
  { country: "Slovakia", dialCode: "+421", iso2: "SK" },
  { country: "Slovenia", dialCode: "+386", iso2: "SI" },
  { country: "Solomon Islands", dialCode: "+677", iso2: "SB" },
  { country: "Somalia", dialCode: "+252", iso2: "SO" },
  { country: "South Africa", dialCode: "+27", iso2: "ZA" },
  { country: "South Korea", dialCode: "+82", iso2: "KR" },
  { country: "South Sudan", dialCode: "+211", iso2: "SS" },
  { country: "Spain", dialCode: "+34", iso2: "ES" },
  { country: "Sri Lanka", dialCode: "+94", iso2: "LK" },
  { country: "Sudan", dialCode: "+249", iso2: "SD" },
  { country: "Suriname", dialCode: "+597", iso2: "SR" },
  { country: "Sweden", dialCode: "+46", iso2: "SE" },
  { country: "Switzerland", dialCode: "+41", iso2: "CH" },
  { country: "Syria", dialCode: "+963", iso2: "SY" },
  { country: "Taiwan", dialCode: "+886", iso2: "TW" },
  { country: "Tajikistan", dialCode: "+992", iso2: "TJ" },
  { country: "Tanzania", dialCode: "+255", iso2: "TZ" },
  { country: "Thailand", dialCode: "+66", iso2: "TH" },
  { country: "Timor-Leste", dialCode: "+670", iso2: "TL" },
  { country: "Togo", dialCode: "+228", iso2: "TG" },
  { country: "Tokelau", dialCode: "+690", iso2: "TK" },
  { country: "Tonga", dialCode: "+676", iso2: "TO" },
  { country: "Trinidad and Tobago", dialCode: "+1", iso2: "TT" },
  { country: "Tunisia", dialCode: "+216", iso2: "TN" },
  { country: "Turkey", dialCode: "+90", iso2: "TR" },
  { country: "Turkmenistan", dialCode: "+993", iso2: "TM" },
  { country: "Turks and Caicos Islands", dialCode: "+1", iso2: "TC" },
  { country: "Tuvalu", dialCode: "+688", iso2: "TV" },
  { country: "Uganda", dialCode: "+256", iso2: "UG" },
  { country: "Ukraine", dialCode: "+380", iso2: "UA" },
  { country: "United Arab Emirates", dialCode: "+971", iso2: "AE" },
  { country: "United Kingdom", dialCode: "+44", iso2: "GB" },
  { country: "United States", dialCode: "+1", iso2: "US" },
  { country: "Uruguay", dialCode: "+598", iso2: "UY" },
  { country: "Uzbekistan", dialCode: "+998", iso2: "UZ" },
  { country: "Vanuatu", dialCode: "+678", iso2: "VU" },
  { country: "Vatican City", dialCode: "+379", iso2: "VA" },
  { country: "Venezuela", dialCode: "+58", iso2: "VE" },
  { country: "Vietnam", dialCode: "+84", iso2: "VN" },
  { country: "Yemen", dialCode: "+967", iso2: "YE" },
  { country: "Zambia", dialCode: "+260", iso2: "ZM" },
  { country: "Zimbabwe", dialCode: "+263", iso2: "ZW" },
];

export function formatValidPhoneNumber(countryCode: string, mobile: string): string | null {
  const phoneNumber = parsePhoneNumberFromString(`${countryCode}${mobile}`);

  if (!phoneNumber?.isValid()) {
    return null;
  }

  return phoneNumber.number;
}

const NON_DIGITS_REGEX = /\D+/g;

// Mirrors `common_gateway_service.utils.phone.format_valid_phone_number`:
// - empty/whitespace -> empty string
// - strips non-digits
// - if digits < 6 -> invalid (null)
// - prefixes "+" to the country code digits when present
export function formatGatewayPhoneNumber(countryCode: string | null | undefined, mobile: string | null | undefined): string | null {
  const mobileDigits = (mobile ?? "").replace(NON_DIGITS_REGEX, "");
  if (!mobileDigits) return "";

  if (mobileDigits.length < 6) return null;

  let ccDigits = (countryCode ?? "").replace(NON_DIGITS_REGEX, "");
  if (ccDigits && !ccDigits.startsWith("+")) {
    ccDigits = `+${ccDigits}`;
  }

  return ccDigits ? `${ccDigits}${mobileDigits}` : mobileDigits;
}
